import { defineConfig } from "vitepress";
import markdownItFootnote from "markdown-it-footnote";

const description =
  "A zsh plugin for timing, working with, and displaying the time an interactive shell command takes to execute.";
const title = "command-execution-timer";

// https://vitepress.dev/reference/site-config
export default defineConfig({
  head: [
    // favicon generated by https://realfavicongenerator.net/
    [
      "link",
      {
        rel: "icon",
        type: "image/png",
        sizes: "48x48",
        href: "/favicon-48x48.png",
      },
    ],
    [
      "link",
      {
        rel: "icon",
        type: "image/svg+xml",
        href: "/favicon.svg",
      },
    ],
    [
      "link",
      {
        rel: "shortcut icon",
        href: "/favicon.ico",
      },
    ],
    [
      "link",
      {
        rel: "apple-touch-icon",
        sizes: "180x180",
        href: "/apple-touch-icon.png",
      },
    ],
    [
      "link",
      {
        rel: "manifest",
        href: "/site.webmanifest",
      },
    ],

    // social metas
    ["meta", { property: "og:title", content: "command-execution-timer" }],
    [
      "meta",
      {
        property: "og:description",
        content: description,
      },
    ],
    [
      "meta",
      {
        property: "og:url",
        content: "https://command-execution-timer.olets.dev/",
      },
    ],
    ["meta", { property: "og:site_name", content: "command-execution-timer" }],
    ["meta", { property: "og:type", content: "website" }],
    [
      "meta",
      {
        property: "og:image",
        content:
          "https://command-execution-timer.olets.dev/command-execution-timer-card.png",
      },
    ],
    ["meta", { property: "og:image:width", content: "1200" }],
    ["meta", { property: "og:image:height", content: "630" }],
    ["meta", { name: "twitter:title", content: "command-execution-timer" }],
    ["meta", { name: "twitter:card", content: "summary_large_image" }],
    [
      "meta",
      {
        name: "twitter:description",
        content: description,
      },
    ],
    [
      "meta",
      {
        name: "twitter:image",
        content:
          "https://command-execution-timer.olets.dev/command-execution-timer-card.png",
      },
    ],

    // Analytics
    [
      "script",
      {
        src: "https://cdn.usefathom.com/script.js",
        "data-site": "GOPIVWSF",
        "data-spa": "auto",
        defer: "true",
      },
    ],
    [
      "script",
      {
        src: "/js/analytics.js",
      },
    ],

    // Font
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.googleapis.com",
      },
    ],
    [
      "link",
      {
        rel: "preconnect",
        href: "https://fonts.gstatic.com",
        crossorigin: "true",
      },
    ],
    [
      "link",
      {
        href: "https://fonts.googleapis.com/css2?family=Fira+Code&display=swap",
        rel: "stylesheet",
      },
    ],
  ],
  title: title,
  description: description,
  // https://vitepress.dev/reference/site-config#titletemplate
  titleTemplate: `:title :: ${title}`, // to change delimiter from default pipe to play nice with Fathom event id format. see also homepage frontmatter
  // https://vitepress.dev/reference/default-theme-last-updated
  lastUpdated: true,
  markdown: {
    externalLinks: {
      class: "vp-external-link-icon",
      target: "_self",
    },
    config: (md) => {
      md.use(markdownItFootnote);
    },
    theme: {
      light: "github-light-high-contrast",
      dark: "github-dark-high-contrast",
    },
  },
  srcExclude: ["vitepressignore"],
  sitemap: {
    hostname: "https://command-execution-timer.olets.dev",
  },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config

    editLink: {
      pattern:
        "https://github.com/olets/command-execution-timer/edit/main/docs/:path",
    },

    logo: "/images/command-execution-timer-logo.png",

    nav: [
      {
        text: "Source, Changelog, License",
        link: "https://github.com/olets/command-execution-timer/",
        target: "_self",
      },
      {
        text: "olets.dev",
        link: "https://olets.dev",
        target: "_self",
      },
    ],

    search: {
      provider: "local",
    },

    sidebar: [
      { text: "Overview", link: "/" },
      { text: "Installation", link: "/installation" },
      { text: "Usage", link: "/usage" },
      { text: "Options", link: "/options" },
      { text: "Contributing", link: "/contributing" },
      { text: "Acknowledgments", link: "/acknowledgments" },
    ],
  },
});
